env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download

builds:
  -
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - arm64
      - amd64

archives:
  -
    replacements:
      arm64: arm64
      amd64: x86_64
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'
